export * from './pages/home.page'
export * from './components/home-blog/home-blog.component'
export * from './components/home-easy-access/home-easy-access.component'
export * from './components/home-news/home-news.component'
export * from './components/home-crypto/home-crypto.component'